### ISSUE TITLE
Invalid sequence set when listing envelopes

### ISSUE THREAD

**Issue by edwardzcn-decade** [pimalaya/himalaya#518]
Hi, I use IMAP to test one email account. After setting the configuration and solving the tls problem. Finally, envelope list only work for 1 mail which send/receieve by my self.

you can see from the output: 1

```
2024-12-10T09:44:07.320899Z DEBUG email::email::envelope::list::imap: found 1 imap envelopes

| ID               | FLAGS             | SUBJECT            | FROM                      | DATE                              |
|------------------|-------------------|--------------------|---------------------------|-----------------------------------|
| 1242             |                   | Hihi               | Chuannan Zhang            | 2024-12-10 17:26+08:00            |
```

## Bug

Next I send a test email (with only 'test' body) from gmail/output. And himalaya return error. Seems it successfully links to the INBOX and finds `exists(2)` with the incoming mail. But it cant resolve the IMAP task.

```
2024-12-10T09:39:22.663292Z DEBUG keyring::service: define global service name name="himalaya-cli"
2024-12-10T09:39:22.670467Z  INFO himalaya::email::envelope::command::list: executing list envelopes command
2024-12-10T09:39:22.672094Z DEBUG email::imap: building 1 IMAP clients
2024-12-10T09:39:22.680882Z DEBUG client::build: rustls::client::hs: No cached session for DnsName("imap.qq.com")    
2024-12-10T09:39:22.681651Z DEBUG client::build: rustls::client::hs: Not resuming any session    
2024-12-10T09:39:22.736403Z DEBUG client::build: rustls::client::hs: ALPN protocol is None    
2024-12-10T09:39:22.736420Z DEBUG client::build: rustls::client::hs: Using ciphersuite TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256    
2024-12-10T09:39:22.736720Z DEBUG client::build: rustls::client::tls12: ECDHE curve is EcParameters { curve_type: NamedCurve, named_group: secp256r1 }    
2024-12-10T09:39:22.736729Z DEBUG client::build: rustls::client::tls12: Server DNS name is DnsName("imap.qq.com")    
2024-12-10T09:39:23.102235Z DEBUG client::build: email::imap: using password authentication
2024-12-10T09:39:23.102304Z  INFO client::build: process::command: run shell command cmd="pass show qqmail"
2024-12-10T09:39:23.102314Z DEBUG client::build: process::command: inherit stdin from parent
2024-12-10T09:39:23.102320Z DEBUG client::build: process::command: stdout piped
2024-12-10T09:39:23.102324Z DEBUG client::build: process::command: stderr piped
2024-12-10T09:39:23.342150Z DEBUG client::build: process::command: shell command gracefully exited code=0
2024-12-10T09:39:23.342386Z DEBUG client::build: email::imap: supported auth mechanisms mechanisms=[Plain, Login, XOAuth2]
2024-12-10T09:39:23.342401Z DEBUG client::build: email::imap: trying auth mechanism… mechanism=Plain
2024-12-10T09:39:23.589632Z DEBUG client::build: email::imap: authentication succeeded! mechanism=Plain
2024-12-10T09:39:23.591261Z  INFO email::email::envelope::list::imap: listing IMAP envelopes from mailbox INBOX
2024-12-10T09:39:23.591714Z DEBUG email::imap: client 1/1 is free, locking it
2024-12-10T09:39:23.592300Z DEBUG email::email::envelope::list::imap: UTF7-encoded mailbox name="INBOX"
2024-12-10T09:39:23.713906Z  WARN select_mailbox{client=1}: imap_codec::response: Rectified missing `text` to "..."    
2024-12-10T09:39:23.713993Z DEBUG email::email::envelope::list::imap: mailbox selected name="INBOX" data=SelectDataUnvalidated { flags: Some([Answered, Flagged, Deleted, Draft, Seen]), exists: Some(2), recent: Some(0), unseen: Some(1), permanent_flags: Some([Asterisk, Flag(Answered), Flag(Flagged), Flag(Deleted), Flag(Draft), Flag(Seen)]), uid_next: Some(1247), uid_validity: Some(1517461405) }
Error: 
   0: cannot fetch IMAP messages
   1: cannot resolve IMAP task
   2: unexpected BAD response: Sequence set is inavlid!

Location:
   /Users/edwardzcn-mini/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pimalaya-tui-0.2.1/src/himalaya/backend.rs:513
```

**Comment by edwardzcn-decade** [comment]
It does work with `--page-size 0` param. Here is the result:

![image](https://github.com/user-attachments/assets/8a3657fd-8390-424a-a30e-46b88427d16d)

But why I need this param. I find the explanation in the samle toml config that `customize the number of envelopes to show by page`.

> Would it be possible for you to create us a fake account there, so I could debug? You can send me credentials either as a private message on the Matrix chat, or by email at: clement.douin at posteo.net

Sry that I could not provide you a fake account to test. In short, the qq.com mail service asks for phone number registered with ID card :( However, is it possible to hypothesize the path (e.g., whether it lies in the client or the core dependency) based on the trace information in the first paragraph? I will continue conducting some tests in this area.

BTW, I use Gmail  in my daily workflow. However, as I mentioned in the core repository issue, this requires [proxy feature support](https://github.com/pimalaya/core/issues/17#issue) in advance.

**Comment by soywod** [comment]
> But why I need this param. I find the explanation in the sample config that `customize the number of envelopes to show by page`.

When using `--page-size 0` you disable the pagination, therefore the IMAP sequence sent is not the same (`1:*`). I don't get why the server sends an error on the sequence set received. Unfortunately the sequence is not logged. I will add a log soon, then you can either wait for the next patch release or build from sources (using Cargo directly).

**Comment by DreamMaoMao** [comment]
I also have this problem, but I can use imap.qq.com mailbox in aerc.

**Comment by DreamMaoMao** [comment]
```
2024-12-29T00:00:29.554522Z DEBUG list_envelopes{folder="INBOX" opts=ListEnvelopesOptions { page_size: 10, page: 0, query: None }}: email::email::envelope::list::imap: UTF7-encoded mailbox name="INBOX"
2024-12-29T00:00:29.554631Z TRACE list_envelopes{folder="INBOX" opts=ListEnvelopesOptions { page_size: 10, page: 0, query: None }}:select_mailbox{client=1}: imap_client::stream: wrote 27/27 bytes
2024-12-29T00:00:29.625562Z TRACE list_envelopes{folder="INBOX" opts=ListEnvelopesOptions { page_size: 10, page: 0, query: None }}:select_mailbox{client=1}: imap_client::stream: read 298/1024 bytes
2024-12-29T00:00:29.625686Z  WARN list_envelopes{folder="INBOX" opts=ListEnvelopesOptions { page_size: 10, page: 0, query: None }}:select_mailbox{client=1}: imap_client::tasks::tasks::select: missing required UNSEEN OK untagged response
2024-12-29T00:00:29.625719Z DEBUG list_envelopes{folder="INBOX" opts=ListEnvelopesOptions { page_size: 10, page: 0, query: None }}: email::email::envelope::list::imap: mailbox selected name="INBOX" data=SelectDataUnvalidated { flags: Some([Answered, Flagged, Deleted, Draft, Seen]), exists: Some(7), recent: Some(0), unseen: None, permanent_flags: Some([Asterisk, Flag(Answered), Flag(Flagged), Flag(Deleted), Flag(Draft), Flag(Seen)]), uid_next: Some(3693), uid_validity: Some(1415888772) }
2024-12-29T00:00:29.625882Z TRACE list_envelopes{folder="INBOX" opts=ListEnvelopesOptions { page_size: 10, page: 0, query: None }}:fetch_envelopes_by_sequence{client=1}: imap_client::stream: wrote 59/59 bytes
2024-12-29T00:00:29.685929Z TRACE list_envelopes{folder="INBOX" opts=ListEnvelopesOptions { page_size: 10, page: 0, query: None }}:fetch_envelopes_by_sequence{client=1}: imap_client::stream: read 43/1024 bytes
Error: 
   0: cannot fetch IMAP messages
   1: cannot resolve IMAP task
   2: unexpected BAD response: Sequence set is inavlid!

```

**Comment by soywod** [comment]
I will add the log for the next patch release. From there we will be able to debug properly this issue.

**Comment by soywod** [comment]
Fixed on `master`, should be part of the next patch release.

**Comment by soywod** [comment]
New release [`v1.1.0`](https://github.com/pimalaya/himalaya/releases/tag/v1.1.0) out, could you share the new trace logs?

**Comment by soywod** [comment]
```text
SequenceSet([Range(Value(175), Value(166))]+)
```

I bet the server does not appreciate the range order. As far as I remember, the range should be commutative. `175:166` should be the same as `166:175`. But I cannot find back this information in RFCs, any idea @duesee?

**Comment by soywod** [comment]
Just found back in [RFC 3501](https://datatracker.ietf.org/doc/html/rfc3501#page-90):

```abnf
seq-range       = seq-number ":" seq-number
                    ; two seq-number values and all values between
                    ; these two **regardless of order**.
                    ; Example: 2:4 and 4:2 are equivalent and indicate
                    ; values 2, 3, and 4.
                    ; Example: a unique identifier sequence range of
                    ; 3291:* includes the UID of the last message in
                    ; the mailbox, even if that value is less than 3291.
```

**Comment by duesee** [comment]
You were faster, hehe :-) The order should not be important. AFAIR, imap-types already reorders accordingly when, e.g., iterating over a sequence. Do you think it makes sense to always reorder and take away the possibility to send descending sequences in imap-types? This could be a measure to protect ourselves against faulty servers...

**Comment by duesee** [comment]
Context: https://github.com/duesee/imap-codec/issues/411 We had the same bug but resolved it.

**Comment by soywod** [comment]
> Hmm... maybe some implementation wants to get messages in reversed order? Say... you want to fetch 100:1 starting with 100. When we exclude this possibility, people would need to write 100,99,98,... manually. Not sure...

Well, according to the RFC we should not be able to do that, since the sequence is re-ordered at request level:

```
Example: 2:4 and 4:2 are equivalent and indicate values 2, 3, and 4.
```

It seems just not possible to ask for 4, 3 then 2 using sequence set.

> Context: [duesee/imap-codec#411](https://github.com/duesee/imap-codec/issues/411) We had the same bug but resolved it.

Awesome, I checked and indeed it should fix this particular issue as well. Let's wait for the `v2` then 🙂

**Comment by duesee** [comment]
> Awesome, I checked and indeed it should fix this particular issue as well. Let's wait for the v2 then 🙂

Oh, no. What I meant was that when you iterate through a sequence set, it resolves now correctly. But this is rather only done when imap-types is used for a server.

As a client you can still send 5:1, which, to my understanding, would break the server. In this case the user of imap-types needs to ensure to use 1:5 instead of 5:1. But maybe it's a good idea to transparently change 5:1 to 1:5 in imap-types then indeed...

**Comment by soywod** [comment]
> But maybe it's a good idea to transparently change 5:1 to 1:5 in imap-types then indeed...

Isn't it a perfect use case for introducing a new quirk? Something like `quirk_enforce_ascending_sequence`.

**Comment by duesee** [comment]
Hey! Yes, we can provide it. Happy to review!

**Comment by andyWang1688** [comment]
Validation report from a real-world Tencent Exmail (imap.exmail.qq.com) account:

- Himalaya version: v1.2.0 (Homebrew)
- Account auth: password auth (PLAIN/LOGIN)
- `himalaya envelope list --page-size 10`, `--page-size 50`, `--page-size 100` all worked reliably
- No `Sequence set is inavlid!` error observed

Important trace detail:
- Internal task still showed a descending range in debug struct (`SequenceSet([Range(Value(288), Value(279))])`)
- But the encoded IMAP command sent on wire was normalized ascending: `FETCH 279:288 (...)`

So for this Exmail environment, the #518 symptom appears fixed in v1.2.0.

Note: `--page-size 0` timed out once in my mailbox (likely large mailbox/timeout behavior), but this seems different from the old sequence-set incompatibility issue.
